"""Gate: every claim value matches the reviewed, committed value -- bound to the paper or not.

check_binding.py runs manuscript -> claims: each of the 291 numbers the paper prints must equal
the one claim it is bound to. Because that mapping is total, no printed number lacks a tie. But
219 of the 376 numeric claims are named by no rule, and fault injection found the consequence:
bending rm_buy_hold_sell_marginals_per_config_prevalenc_het_sell from 0.085 to 0.4242 was caught
by nothing, because the manuscript's 0.085 is bound to a different claim that also holds 0.085.

So the claims file is pinned. claims.lock.json records every numeric claim's value as reviewed;
this gate recomputes the claims and compares. The iterations already show claims.json is
regenerated byte-identically from the same code -- the lock adds the part they cannot: whether a
CODE change moved a value that nobody is watching.

  python code/src/check_claims_bound.py
  python code/src/check_claims_bound.py --update   # after an intended change; the diff is printed
                                                   # and lands in the commit for review

Two earlier designs were wrong and are recorded so they are not re-tried.

The first asked "is this claim's value printed in the manuscript?", generating four scales x
five precisions per claim and matching against any literal. That made 2.0 "printed as 2000" and
0.5151 "printed as 0.5" (the chance-level constant): 75 false positives, and the
generated-candidate anti-pattern this artifact had just removed from check_coverage.py.

The second recorded, for each unbound claim, a BOUND claim carrying the same value and asserted
the two stay equal. But a generator cannot establish that two keys are the same QUANTITY, and
most pairs it produced merely coincided -- a temperature kappa of 0.384 twinned to a Wilson
interval bound of 0.384, 3600 xAI calls twinned to 3600 scoreable decisions. Enforcing those
equalities would fail the moment one legitimately moved. Pinning a value asserts only what is
true: this number was reviewed and has not changed.
"""
from __future__ import annotations
import importlib.util
import json
import math
import sys
from pathlib import Path

# Exact == fails across OS/CPU: Code Ocean Linux and a Mac lock file disagree at ~1e-12
# to 1e-14 on the same analysis. The paper prints 3–4 decimals (~1e-4); 1e-8 absorbs
# platform noise and still flags a real fourth-decimal move.
_LOCK_REL = 1e-8
_LOCK_ABS = 1e-12


def _same(a: float, b: float) -> bool:
    return math.isclose(a, b, rel_tol=_LOCK_REL, abs_tol=_LOCK_ABS)

ROOT = Path(__file__).resolve().parents[2]
CLAIMS = ROOT / "results" / "latest" / "claims.json"
BINDING = Path(__file__).resolve().parent / "check_binding.py"
LOCK = Path(__file__).resolve().parent / "claims.lock.json"


def bound_keys():
    """The claim keys check_binding.R names, or None if that gate is not published here."""
    if not BINDING.exists():
        return None
    spec = importlib.util.spec_from_file_location("_cb", BINDING)
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return {r[2] for r in m.R if not r[2].startswith("!")}


def main() -> int:
    if not CLAIMS.exists():
        print("[claims-lock] claims.json absent -- run make_claims.py")
        return 2
    claims = json.loads(CLAIMS.read_text())
    nums = {k: float(v) for k, v in claims.items()
            if isinstance(v, (int, float)) and not isinstance(v, bool)}
    bound = bound_keys()

    if "--update" in sys.argv:
        old = json.loads(LOCK.read_text())["values"] if LOCK.exists() else {}
        LOCK.write_text(json.dumps({"values": {k: nums[k] for k in sorted(nums)}},
                                   indent=2, sort_keys=True) + "\n")
        moved = [(k, old[k], nums[k]) for k in sorted(nums)
                 if k in old and not _same(old[k], nums[k])]
        added = sorted(set(nums) - set(old))
        gone = sorted(set(old) - set(nums))
        print(f"[claims-lock] wrote {LOCK.relative_to(ROOT)}: {len(nums)} values")
        for k, a, b in moved:
            print(f"    MOVED   {k}: {a} -> {b}")
        for k in added:
            print(f"    ADDED   {k} = {nums[k]}")
        for k in gone:
            print(f"    REMOVED {k} (was {old[k]})")
        if moved or gone:
            print("  Every line above changes a number the artifact reports. The commit diff is "
                  "the review surface -- say in the message why each one moved.")
        return 0

    if not LOCK.exists():
        print(f"[claims-lock] {LOCK.relative_to(ROOT)} absent -- create it with --update and "
              f"review the values it records")
        return 2
    locked = json.loads(LOCK.read_text())["values"]

    fails = []
    for k in sorted(set(locked) | set(nums)):
        if k not in nums:
            fails.append(f"{k} is pinned at {locked[k]} but the analysis no longer produces it")
        elif k not in locked:
            fails.append(f"{k} = {nums[k]} is new and unpinned -- run --update and review it")
        elif not _same(locked[k], nums[k]):
            tag = "" if bound is None else (" [bound to the manuscript]" if k in bound
                                           else " [not bound to the manuscript]")
            fails.append(f"{k} moved: pinned {locked[k]}, analysis now gives {nums[k]}{tag}")

    nb = "" if bound is None else (f"; {len(bound & set(nums))} of them bound to a manuscript "
                                  f"occurrence, {len(set(nums) - bound)} pinned here only")
    print(f"[claims-lock] {len(nums)} numeric claims match their pinned values{nb}")
    for f in fails:
        print(f"  {f}")
    if fails:
        print(f"[claims-lock] {len(fails)} claim(s) differ from the reviewed values. If the "
              f"change is intended, run --update and explain it in the commit.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
