#!/usr/bin/env bash
# Build the "Highlighted PDF" required by the IEEE Access resubmission checklist: the
# revised manuscript with every individual change marked in yellow.
#
# The highlighted PDF is NOT a second compilation. It is main_manuscript.pdf with the changes
# painted onto it by highlight_overlay.py, so the two files agree line for line and page for
# page -- which is the whole point of a highlighted copy, since a reviewer reads the two side by
# side. Compiling a second document with soul's \texthl could not do that: soul cannot hyphenate
# inside a highlight, so highlighted paragraphs broke differently and four of fourteen pages
# started a line out. Compiling with zero-width \pdfsavepos markers instead fails the same way,
# because a whatsit suppresses hyphenation of the word after it.
#
# latexdiff still defines what "changed" means; only the rendering moved.
#
#   bash submission/build_highlighted.sh            # against the as-submitted tag
#   bash submission/build_highlighted.sh <ref>      # against another ref
set -euo pipefail
cd "$(dirname "$0")/.."
export PATH="$HOME/Library/TinyTeX/bin/universal-darwin:$PATH"
# The baseline is the version the reviewers read, which is a fixed point in history -- not
# "whatever was committed last". This defaulted to HEAD, which worked only while the revision
# was uncommitted; committing it moved the baseline onto the revision itself and the next build
# failed outright. A tag keeps it pinned.
BASE_REF="${1:-as-submitted}"
# pymupdf is required to paint the overlay; bare python3 on some machines is 3.9 without it.
PY="${PY:-}"
if [[ -z "$PY" ]]; then
  for c in "$PWD/.venv/bin/python" "$(command -v python3.12 || true)" \
           "$(command -v python3.11 || true)" "$(command -v python3 || true)"; do
    if [[ -x "$c" ]] && "$c" -c "import pymupdf" >/dev/null 2>&1; then PY="$c"; break; fi
  done
fi
[[ -n "$PY" ]] || { echo "build_highlighted: no interpreter with pymupdf" >&2; exit 2; }
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

if ! git rev-parse --verify --quiet "$BASE_REF^{commit}" >/dev/null; then
  echo "ERROR: baseline ref '$BASE_REF' does not exist. The highlighted PDF must be diffed" >&2
  echo "       against the manuscript as submitted; create the tag with:" >&2
  echo "         git tag -a as-submitted <commit> -m 'Manuscript as submitted'" >&2
  exit 3
fi
git show "$BASE_REF:paper/main.tex" > "$WORK/old.tex"
cp paper/main.tex "$WORK/new.tex"

# Paper 2 held its reordered bibliography and its rounding-only corrections constant
# across the diff. Neither applies here: this revision does not reorder the reference
# list and introduces no digit-level corrections, so nothing is withheld from the
# markup and every change in the manuscript is highlighted.

# --append-textcmd=tfootnote: latexdiff will not descend into \tfootnote, so a change
# inside the IEEE Access title-block footnote would be replaced wholesale and render
# unhighlighted. Without
# this latexdiff replaces the whole \tfootnote command -- \DIFaddbegin \tfootnote{...}
# \DIFaddend rather than \DIFadd{...} around the changed words -- and since only \DIFadd is
# mapped to \texthl, the new date rendered plain. A reviewer comparing the two PDFs saw the
# date change with no mark on it.
# VERBATIMENV=lstlisting: without it latexdiff diffs INSIDE the code listing and emits its
# "%DIF <" / "%DIF >" markers as literal verbatim lines, so the highlighted PDF carried text the
# manuscript does not have and stopped rebuilding from the markup. With it, the old listing
# becomes real LaTeX comments and the new listing is typeset exactly as in main.tex.
latexdiff --type=CFONT --math-markup=0 --append-textcmd="tfootnote" \
          --config="VERBATIMENV=lstlisting" \
          "$WORK/old.tex" "$WORK/new.tex" > "$WORK/diff.tex" 2>/dev/null || true
# markup rewriting is no longer needed: nothing is recompiled

# The reference list is generated by bibtex from references.bib, so a \bibitem added in this
# revision exists in no .tex file and latexdiff can never mark it. main.bbl, written by the
# manuscript build, is passed to the overlay so new entries are highlighted in the printed
# reference list alongside everything else.
"$PY" submission/highlight_overlay.py \
      submission/main_manuscript.pdf "$WORK/diff.tex" submission/highlighted_pdf.pdf \
      "$WORK/old.tex" "$WORK/new.tex" paper/main.bbl
echo "   -> submission/highlighted_pdf.pdf"
